In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
df_weather = pd.read_csv("Fire_temp_2017_clim.csv")

In [24]:
df_tubbs_oct_2017 = df_weather[df_weather.Month == 'October']
df_tubbs_oct_2017

Tubss         Lon       Lat    Month  tmax_2017  tmin_2017
45   CP1 -122.900000  38.40000  October  24.667259   7.222384
46   CP2 -122.500000  38.60000  October  23.910522   8.410995
47   CP3 -122.900000  38.40000  October  24.667259   7.222384
48   CP4 -122.500000  38.70000  October  24.934208   7.891125
49   CP5 -122.720306  38.44466  October  26.242319   8.074903

In [34]:
df_weather_rcp45 = pd.read_csv("RCP45_mean_tmax_tmin_2090.csv")
df_weather_rcp45_oct = df_weather_rcp45[df_weather_rcp45.Month == 'October']
rcp45_oct_max_temperature_diff = df_weather_rcp45_oct["Tmax"] - df_tubbs_oct_2017["tmax_2017"]
rcp_45_max_add = rcp45_oct_max_temperature_diff.max()
rcp_45_max_add

3.2157919400000026

In [35]:
rcp45_oct_min_temperature_diff = df_weather_rcp45_oct["Tmin"] - df_tubbs_oct_2017["tmin_2017"]
rcp_45_min_add = rcp45_oct_min_temperature_diff.max()
rcp_45_min_add

3.583875175

In [36]:
df_weather_rcp85 = pd.read_csv("Mean_all_models_future_2090.csv")
df_weather_rcp85_oct = df_weather_rcp85[df_weather_rcp85.Month == 'October']
rcp85_oct_max_temperature_diff = df_weather_rcp85_oct["tmax_RCP85"] - df_tubbs_oct_2017["tmax_2017"]
rcp85_oct_max_add = rcp85_oct_max_temperature_diff.max()
rcp85_oct_max_add

6.04079222

In [37]:
rcp85_oct_min_temperature_diff = df_weather_rcp85_oct["tmin_RCP85"] - df_tubbs_oct_2017["tmin_2017"]
rcp85_oct_min_add = rcp85_oct_min_temperature_diff.max()
rcp85_oct_min_add

6.308875325

In [43]:
a = np.array([[42, 84, 76, 17],
[46, 84, 86, 13],
[46, 85, 96, 8],
[65, 82, 66, 9],
[46, 78, 90, 20],
[44, 72, 97, 29],
[40, 71, 83, 19]])

In [53]:
a[:,0]

array([42, 46, 46, 65, 46, 44, 40])

In [51]:
min_temp_col = a[:,0]
min_temp_col + rcp_45_min_add*1.8

array([48.45097532, 52.45097532, 52.45097532, 71.45097531, 52.45097532,
       50.45097532, 46.45097532])

In [52]:
max_temp_col = a[:,1]
max_temp_col + rcp_45_max_add*1.8

array([89.78842549, 89.78842549, 90.78842549, 87.78842549, 83.78842549,
       77.78842549, 76.78842549])

In [55]:
min_temp_col = a[:,0]
min_temp_col + rcp85_oct_min_add*1.8

array([53.35597558, 57.35597558, 57.35597558, 76.35597558, 57.35597558,
       55.35597558, 51.35597558])

In [57]:
max_temp_col = a[:,1]
max_temp_col + rcp85_oct_max_add*1.8

array([94.873426, 94.873426, 95.873426, 92.873426, 88.873426, 82.873426,
       81.873426])

In [ ]:
f_increase = 

In [7]:
max_value = column.max()
max_value

26.24231911

In [8]:
min_value_2017 = column_min_2017.max()
min_value_2017

8.410995482999999

In [9]:
df_weather_2090 = pd.read_csv("Fire_temp_2090_clim_V2.csv")
df_weather_2090_oct = df_weather_2090[df_weather_2090.Month == 'October']

In [12]:
column_2090 = df_weather_2090_oct["tmax_RCP85"]
max_value_2090 = column_2090.max()

In [13]:
max_value_2090 

33.90000153

In [34]:
column_min_2090 = df_weather_2090["tmin_RCP85"]
min_value_2090 = column_min_2090.max()
min_value_2090

21.10000038

In [37]:
min_gap = min_value_2090 - min_value_2017
min_gap

12.689004897000002

In [42]:
max_gap = max_value_2090 - max_value

In [25]:
28.8889 + 13.25768089

42.146580889999996

In [26]:
29.4444 + 13.25768089

42.702080890000005

In [27]:
27.7778 + 13.25768089

41.03548089

In [28]:
25.5556 + 13.25768089

38.81328089

In [29]:
22.2222 + 13.25768089

35.479880890000004

In [38]:
5.55556 + min_gap

18.244564897000004

In [39]:
7.77778 + min_gap

20.466784897000004

In [40]:
18.3333 + min_gap

31.022304897000005

In [41]:
6.66667 + min_gap

19.355674897

In [43]:
22.2222 + max_gap

35.479880890000004

In [44]:
4.44444 + min_gap

17.133444897000004

In [45]:
21.6667 + max_gap

34.924380889999995